# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\eclipse\workspace\advanced_search\src\advanced_search_pkg\searchwidget.ui'
#
# Created: Mon Jul 20 18:56:47 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_searchwidget(object):
    def setupUi(self, searchwidget):
        searchwidget.setObjectName("searchwidget")
        searchwidget.resize(713, 668)
        self.gridLayout = QtGui.QGridLayout(searchwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(searchwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pathedit = QtGui.QLineEdit(self.layoutWidget)
        self.pathedit.setMinimumSize(QtCore.QSize(0, 25))
        self.pathedit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pathedit.setObjectName("pathedit")
        self.verticalLayout.addWidget(self.pathedit)
        self.tree = QtGui.QTreeWidget(self.layoutWidget)
        self.tree.setHeaderHidden(True)
        self.tree.setObjectName("tree")
        self.verticalLayout.addWidget(self.tree)
        self.about = QtGui.QPushButton(self.layoutWidget)
        self.about.setObjectName("about")
        self.verticalLayout.addWidget(self.about)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchedit = QtGui.QLineEdit(self.layoutWidget1)
        self.searchedit.setMinimumSize(QtCore.QSize(0, 25))
        self.searchedit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.searchedit.setObjectName("searchedit")
        self.horizontalLayout_2.addWidget(self.searchedit)
        self.clearsearchedit = QtGui.QPushButton(self.layoutWidget1)
        self.clearsearchedit.setMinimumSize(QtCore.QSize(25, 25))
        self.clearsearchedit.setMaximumSize(QtCore.QSize(25, 25))
        self.clearsearchedit.setObjectName("clearsearchedit")
        self.horizontalLayout_2.addWidget(self.clearsearchedit)
        self.statebutton = QtGui.QPushButton(self.layoutWidget1)
        self.statebutton.setMinimumSize(QtCore.QSize(25, 25))
        self.statebutton.setMaximumSize(QtCore.QSize(25, 25))
        self.statebutton.setObjectName("statebutton")
        self.horizontalLayout_2.addWidget(self.statebutton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dircb = QtGui.QCheckBox(self.layoutWidget1)
        self.dircb.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dircb.setChecked(True)
        self.dircb.setObjectName("dircb")
        self.horizontalLayout.addWidget(self.dircb)
        self.filescb = QtGui.QCheckBox(self.layoutWidget1)
        self.filescb.setMaximumSize(QtCore.QSize(16777215, 25))
        self.filescb.setChecked(True)
        self.filescb.setObjectName("filescb")
        self.horizontalLayout.addWidget(self.filescb)
        self.systemcb = QtGui.QCheckBox(self.layoutWidget1)
        self.systemcb.setObjectName("systemcb")
        self.horizontalLayout.addWidget(self.systemcb)
        self.hiddencb = QtGui.QCheckBox(self.layoutWidget1)
        self.hiddencb.setChecked(True)
        self.hiddencb.setObjectName("hiddencb")
        self.horizontalLayout.addWidget(self.hiddencb)
        self.recursecb = QtGui.QCheckBox(self.layoutWidget1)
        self.recursecb.setMaximumSize(QtCore.QSize(16777215, 25))
        self.recursecb.setChecked(True)
        self.recursecb.setObjectName("recursecb")
        self.horizontalLayout.addWidget(self.recursecb)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.resultslist = QtGui.QListWidget(self.layoutWidget1)
        self.resultslist.setObjectName("resultslist")
        self.verticalLayout_3.addWidget(self.resultslist)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(searchwidget)
        QtCore.QObject.connect(self.clearsearchedit, QtCore.SIGNAL("clicked()"), self.searchedit.clear)
        QtCore.QMetaObject.connectSlotsByName(searchwidget)

    def retranslateUi(self, searchwidget):
        searchwidget.setWindowTitle(QtGui.QApplication.translate("searchwidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.headerItem().setText(0, QtGui.QApplication.translate("searchwidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.about.setText(QtGui.QApplication.translate("searchwidget", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.dircb.setText(QtGui.QApplication.translate("searchwidget", "Dirs", None, QtGui.QApplication.UnicodeUTF8))
        self.filescb.setText(QtGui.QApplication.translate("searchwidget", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.systemcb.setText(QtGui.QApplication.translate("searchwidget", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.hiddencb.setText(QtGui.QApplication.translate("searchwidget", "Hidden", None, QtGui.QApplication.UnicodeUTF8))
        self.recursecb.setText(QtGui.QApplication.translate("searchwidget", "Recurse", None, QtGui.QApplication.UnicodeUTF8))

